dist: trusty
sudo: true

services:
  - docker

language: node_js
node_js: "10"

os:
  - linux

before_install:
  - docker build -t yukimir/test .
install:
  - bash install_kubectl.sh

script: 
  - bash docker_push.sh
  - bash kube_deploy.sh